<?php declare(strict_types=1);

use Drupal\elmcip_person\Form\Person;

/**
 * Implements hook_entity_presave().
 *
 * @param \Drupal\Core\Entity\EntityInterface $entity
 */
function elmcip_person_entity_presave(Drupal\Core\Entity\EntityInterface $entity) {

  if ($entity->bundle() === 'person') {
    $person = new Person($entity->field_first_name->value,
      $entity->field_middle_name->value,
      $entity->field_last_name->value);
    $entity->title = $person->person_title();
  }
}

/**
 * Implements hook_form_alter().
 *
 * @param $form
 * @param \Drupal\Core\Form\FormStateInterface $form_state
 * @param $form_id
 */
function elmcip_person_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id) {
  if ($form_id === 'node_person_form') {
    $form['title']['#type'] = 'hidden';
    $form['title']['#default_value'] = 'ELMCIP auto generated - dummy';
  }
}
