<?php declare(strict_types=1);

use Drupal\elmcip_person\Form\Person;

/**
 * Implements hook_entity_presave().
 *
 * @param \Drupal\Core\Entity\EntityInterface $entity
 */
function elmcip_person_entity_presave(Drupal\Core\Entity\EntityInterface $entity) {

  if ($entity->bundle() === 'person') {
    $person = new Person($entity->field_first_name->value,
      $entity->field_middle_name->value,
      $entity->field_last_name->value);
    $entity->title = $person->person_title();
  }
}

/**
 * Implements hook_form_FORM_ID_alter.
 *
 * @param $form
 * @param \Drupal\Core\Form\FormStateInterface $form_state
 * @param $form_id
 */
function elmcip_person_form_node_person_edit_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id) {
  $form['title']['#type'] = 'hidden';
}

/**
 * Implements hook_form_FORM_ID_alter.
 *
 * @param $form
 * @param \Drupal\Core\Form\FormStateInterface $form_state
 * @param $form_id
 */
function elmcip_person_form_node_person_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id) {
  $form["title"]["widget"][0]["value"]["#default_value"] = 'ELMCIP auto generated title';
  $form['title']['#type'] = 'hidden';
}
